### ISSUE TITLE
Invalid format

### ISSUE THREAD

**Issue by msteudel** [kakaroto/SWProxy#107]
### Description: 
When I setup the proxy settings before launching the application, I get a Invalid format error message and the game doesn't connection. If I do the set proxy settings right at the download screen. I get logged in I can see a few items show up in the log in the console:
```
Found Summoners War API request : GetFriendRequest

Found Summoners War API request : GetArenaLog

Found Summoners War API request : GetCostumeCollectionList

Found Summoners War API request : CheckDarkPortalStatus
```

I get into the game but I get a bunch of invalid format errors from the game and none of the files get written out.

**ios**: 9.3.2
**swproxy version (latest pulled from github):**
```
username@Marks-Laptop:~/projects/swproxy (master)$ git log
commit 81f043a8bf55bf87db7306650be82d5373c85ae6
Merge: c9c61aa 8042bfa
Author: Leonardo Stern <leonardo.stern@gmail.com>
Date:   Tue Jun 14 07:43:17 2016 -0300

    Merge pull request #103 from Xzandro/master
    
    -added master_id (for monsters) to optimizer.json

```

### Proxy Log Files (Includes both methods I talked about above)

`2016-06-14 08:58:40,056: yapsy - ERROR - Unable to create plugin object: /Users/marksteudel/projects/swproxy/plugins/RunLogger
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/yapsy/PluginManager.py", line 512, in loadPlugins
    plugin_info.plugin_object = self.instanciateElement(element)
  File "/Library/Python/2.7/site-packages/yapsy/PluginManager.py", line 531, in instanciateElement
    return element()
  File "/Users/marksteudel/projects/swproxy/plugins/RunLogger.py", line 130, in __init__
    with open('swproxy.config') as f:
IOError: [Errno 2] No such file or directory: 'swproxy.config'
2016-06-14 08:58:40,058: SWPlugin - INFO - Loaded 7 plugins
2016-06-14 08:58:40,060: proxy - INFO - Starting server on 10.10.10.18, port 8080
2016-06-14 08:58:43,736: proxy - INFO - 10.10.10.15:56681 - GET app-adforce.jp:80/ad//p/tmck?_app=2504&_bundle_id=com.com2us.smon.normal.freefull.apple.kr.ios.universal&_bv=2.1.5&_model=iPhone7%2C2&_os_ver=9.3.2&_sdk_ver=v2.16.3g - 200 OK - 488 bytes
2016-06-14 08:58:44,874: proxy - INFO - 10.10.10.15:56687 - CONNECT itunes.apple.com:443
2016-06-14 08:58:45,186: proxy - INFO - 10.10.10.15:56688 - CONNECT itunes.apple.com:443
2016-06-14 08:58:45,488: proxy - INFO - 10.10.10.15:56689 - CONNECT itunes.apple.com:443
2016-06-14 08:58:45,797: proxy - INFO - 10.10.10.15:56690 - CONNECT itunes.apple.com:443
2016-06-14 08:58:46,163: proxy - INFO - 10.10.10.15:56691 - CONNECT itunes.apple.com:443
2016-06-14 08:58:46,461: proxy - INFO - 10.10.10.15:56692 - CONNECT itunes.apple.com:443
2016-06-14 08:58:46,781: proxy - INFO - 10.10.10.15:56693 - CONNECT itunes.apple.com:443
2016-06-14 08:58:47,034: proxy - INFO - 10.10.10.15:56694 - CONNECT itunes.apple.com:443
2016-06-14 08:58:47,292: proxy - INFO - 10.10.10.15:56695 - CONNECT itunes.apple.com:443
2016-06-14 08:58:47,598: proxy - INFO - 10.10.10.15:56696 - CONNECT itunes.apple.com:443
2016-06-14 08:58:48,953: proxy - INFO - 10.10.10.15:56698 - POST activeuser.qpyou.cn:80/gateway.php - 200 OK - 527 bytes
2016-06-14 08:58:49,612: proxy - INFO - 10.10.10.15:56701 - POST activeuser.qpyou.cn:80/gateway.php - 200 OK - 418 bytes
2016-06-14 08:58:49,627: proxy - INFO - 10.10.10.15:56699 - POST push.qpyou.cn:80/api/register.php - 200 OK - 304 bytes
2016-06-14 08:58:49,627: proxy - INFO - 10.10.10.15:56700 - POST push.qpyou.cn:80/api/register.php - 200 OK - 304 bytes
2016-06-14 08:58:51,975: proxy - INFO - 10.10.10.15:56702 - GET summonerswar-gb.com2us.net:80/api/location_c2.php - 200 OK - 588 bytes
2016-06-14 08:58:52,583: proxy - INFO - 10.10.10.15:56703 - POST summonerswar-gb.qpyou.cn:80/api/server_status_c2.php - 200 OK - 331 bytes
2016-06-14 08:58:53,025: proxy - INFO - 10.10.10.15:56704 - POST summonerswar-gb.qpyou.cn:80/api/version_info_c2.php - 200 OK - 1665 bytes
2016-06-14 08:58:53,399: proxy - INFO - 10.10.10.15:56705 - GET image-glb.qpyou.cn:80/smon/hub_dist/res/download_2.01.08.inf - 200 OK - 1124 bytes
2016-06-14 08:58:55,996: proxy - INFO - 10.10.10.15:56706 - GET image-glb.qpyou.cn:80/smon/hub_dist/banapplist/banapplist.dat - 200 OK - 1552 bytes
2016-06-14 08:58:57,031: proxy - INFO - 10.10.10.15:56707 - POST api.qpyou.cn:80/device/registered - 200 OK - 331 bytes
2016-06-14 08:58:57,933: proxy - INFO - 10.10.10.15:56708 - GET hub.qpyou.cn:80/auth - 302 Moved Temporarily - 764 bytes
2016-06-14 08:58:58,556: proxy - INFO - 10.10.10.15:56710 - POST api.qpyou.cn:80/user/me - 200 OK - 657 bytes
2016-06-14 08:58:58,700: proxy - INFO - 10.10.10.15:56709 - POST friend-api.qpyou.cn:80/api/addressbook/addressbooksynccount - 200 OK - 459 bytes
2016-06-14 08:58:58,890: proxy - INFO - 10.10.10.15:56711 - GET image-glb.qpyou.cn:80/hubweb/hive_img/U/P/130096065/20160107/aea3733945cf73a9b1bdf81f307ef354.jpg - 200 OK - 13017 bytes
2016-06-14 08:58:59,009: proxy - INFO - 10.10.10.15:56712 - POST summonerswar-gb.qpyou.cn:80/api/gateway_c2.php - 200 OK - 448 bytes
2016-06-14 08:59:00,197: proxy - INFO - 10.10.10.15:56713 - POST m-mercury.qpyou.cn:80/init - 200 OK - 375 bytes
2016-06-14 08:59:00,699: proxy - INFO - 10.10.10.15:56714 - POST m-mercury.qpyou.cn:80/init - 200 OK - 679 bytes
2016-06-14 08:59:14,878: proxy - INFO - 10.10.10.15:56682 - CONNECT setting.adzcore.com:443
2016-06-14 08:59:15,756: proxy - INFO - 10.10.10.15:56684 - POST analytics.app-adforce.jp:80/fax/analytics - 200 OK - 110 bytes
2016-06-14 08:59:15,840: proxy - INFO - 10.10.10.15:56683 - CONNECT graph.facebook.com:443
2016-06-14 08:59:16,088: proxy - INFO - 10.10.10.15:56686 - CONNECT live.chartboost.com:443
2016-06-14 08:59:16,088: proxy - INFO - 10.10.10.15:56685 - CONNECT action.adzcore.com:443
2016-06-14 08:59:19,401: proxy - INFO - 10.10.10.15:56697 - CONNECT spreadsheets.google.com:443
2016-06-14 09:00:08,797: proxy - INFO - 10.10.10.15:56715 - CONNECT 169452.engine.mobileapptracking.com:443
2016-06-14 09:00:14,811: proxy - INFO - 10.10.10.15:56716 - POST analytics.app-adforce.jp:80/fax/analytics - 200 OK - 110 bytes
2016-06-14 09:01:14,885: proxy - INFO - 10.10.10.15:56717 - POST analytics.app-adforce.jp:80/fax/analytics - 200 OK - 110 bytes
2016-06-14 09:10:24,640: proxy - INFO - 10.10.10.15:56720 - POST activeuser.qpyou.cn:80/gateway.php - 200 OK - 463 bytes
2016-06-14 09:10:56,375: proxy - INFO - 10.10.10.15:56721 - CONNECT graph.facebook.com:443
2016-06-14 09:10:56,406: proxy - INFO - 10.10.10.15:56718 - POST analytics.app-adforce.jp:80/fax/analytics - 200 OK - 110 bytes
2016-06-14 09:10:56,406: proxy - INFO - 10.10.10.15:56719 - POST analytics.app-adforce.jp:80/fax/analytics - 200 OK - 110 bytes
2016-06-14 09:11:11,717: proxy - INFO - 10.10.10.15:56722 - CONNECT 169452.engine.mobileapptracking.com:443
2016-06-14 09:11:51,639: proxy - INFO - 10.10.10.15:56725 - GET mesu.apple.com:80/assets/com_apple_MobileAsset_SoftwareUpdate/com_apple_MobileAsset_SoftwareUpdate.xml - 304 Not Modified - 272 bytes
2016-06-14 09:12:00,676: proxy - INFO - 10.10.10.15:56729 - CONNECT play.itunes.apple.com:443
2016-06-14 09:12:01,376: proxy - INFO - 10.10.10.15:56731 - CONNECT configuration.apple.com:443
2016-06-14 09:12:01,425: proxy - INFO - 10.10.10.15:56730 - CONNECT init.itunes.apple.com:443
2016-06-14 09:12:32,732: proxy - INFO - 10.10.10.15:56732 - CONNECT xp.apple.com:443
2016-06-14 09:13:16,294: proxy - INFO - 10.10.10.15:56734 - GET mesu.apple.com:80/assets/com_apple_MobileAsset_SoftwareUpdate/com_apple_MobileAsset_SoftwareUpdate.xml - 304 Not Modified - 272 bytes
2016-06-14 09:13:16,845: proxy - INFO - 10.10.10.15:56735 - GET mesu.apple.com:80/assets/com_apple_MobileAsset_SoftwareUpdate/com_apple_MobileAsset_SoftwareUpdate.xml - 304 Not Modified - 272 bytes
2016-06-14 09:13:18,767: proxy - INFO - 10.10.10.15:56736 - GET mesu.apple.com:80/assets/com_apple_MobileAsset_SoftwareUpdate/com_apple_MobileAsset_SoftwareUpdate.xml - 304 Not Modified - 272 bytes
2016-06-14 09:13:19,394: proxy - INFO - 10.10.10.15:56737 - GET mesu.apple.com:80/assets/com_apple_MobileAsset_SoftwareUpdate/com_apple_MobileAsset_SoftwareUpdate.xml - 304 Not Modified - 272 bytes
2016-06-14 09:13:31,425: proxy - INFO - 10.10.10.15:56733 - CONNECT gs-loc.apple.com:443
2016-06-14 09:14:01,765: proxy - INFO - 10.10.10.15:56757 - POST m-mercury.qpyou.cn:80/init - 200 OK - 375 bytes
2016-06-14 09:14:02,345: proxy - INFO - 10.10.10.15:56758 - POST m-mercury.qpyou.cn:80/init - 200 OK - 679 bytes
2016-06-14 09:14:06,285: SWProxy - INFO - Found Summoners War API request : GetFriendRequest
2016-06-14 09:14:06,288: proxy - INFO - 10.10.10.15:56761 - POST summonerswar-gb.qpyou.cn:80/api/gateway_c2.php - 200 OK - 916 bytes
2016-06-14 09:14:06,301: SWProxy - INFO - Found Summoners War API request : GetArenaLog
2016-06-14 09:14:06,302: proxy - INFO - 10.10.10.15:56759 - POST summonerswar-gb.qpyou.cn:80/api/gateway_c2.php - 200 OK - 1301 bytes
2016-06-14 09:14:06,340: proxy - INFO - 10.10.10.15:56762 - POST m-mercury.qpyou.cn:80/init - 200 OK - 825 bytes
2016-06-14 09:14:06,396: proxy - INFO - 10.10.10.15:56760 - POST summonerswar-gb.qpyou.cn:80/api/gateway_c2.php - 200 OK - 448 bytes
2016-06-14 09:14:06,634: SWProxy - INFO - Found Summoners War API request : GetCostumeCollectionList
2016-06-14 09:14:06,635: proxy - INFO - 10.10.10.15:56764 - POST summonerswar-gb.qpyou.cn:80/api/gateway_c2.php - 200 OK - 488 bytes
2016-06-14 09:14:06,656: SWProxy - INFO - Found Summoners War API request : CheckDarkPortalStatus
2016-06-14 09:14:06,657: proxy - INFO - 10.10.10.15:56765 - POST summonerswar-gb.qpyou.cn:80/api/gateway_c2.php - 200 OK - 936 bytes
2016-06-14 09:14:11,883: proxy - INFO - 10.10.10.15:56766 - POST summonerswar-gb.qpyou.cn:80/api/gateway_c2.php - 200 OK - 448 bytes
2016-06-14 09:14:12,118: proxy - INFO - 10.10.10.15:56767 - GET image-glb.qpyou.cn:80/hubweb/hive_img/U/P/101471668/20160214/0636665dd0eb6829f3d6fa525428fe64.jpg - 200 OK - 11092 bytes
2016-06-14 09:14:12,888: proxy - INFO - 10.10.10.15:56768 - GET image-glb.qpyou.cn:80////hubweb/avatar_img/public/smon_22_s.png - 200 OK - 23438 bytes
2016-06-14 09:14:13,521: proxy - INFO - 10.10.10.15:56769 - GET image-glb.qpyou.cn:80/hubweb/hive_img/U/P/146568751/20160613/fd7a138b71a45194e3270a1ed32871ce.jpg - 200 OK - 8955 bytes
2016-06-14 09:14:14,215: proxy - INFO - 10.10.10.15:56770 - GET image-glb.qpyou.cn:80/hubweb/hive_img/U/P/111384065/20160609/c473ef436f2d1dc4619f341899b5d72e.jpg - 200 OK - 11321 bytes
2016-06-14 09:14:14,834: proxy - INFO - 10.10.10.15:56771 - GET image-glb.qpyou.cn:80////hubweb/avatar_img/03377/0202a6/0141a7d/05314a80dd8c1d2982f004f6ec3fb817_public_s.jpg - 200 OK - 10989 bytes
2016-06-14 09:14:16,208: proxy - INFO - 10.10.10.15:56772 - GET image-glb.qpyou.cn:80////hubweb/avatar_img/02ca5/01be78/01170b6/3bd8cf149c82b65347a4c96068f2e46a_public_s.jpg - 200 OK - 13932 bytes
2016-06-14 09:14:16,979: proxy - INFO - 10.10.10.15:56773 - GET image-glb.qpyou.cn:80////hubweb/avatar_img/public/smon_21_s.png - 200 OK - 18811 bytes
2016-06-14 09:14:17,632: proxy - INFO - 10.10.10.15:56774 - GET image-glb.qpyou.cn:80/hubweb/hive_img/U/P/111249579/20160501/73539dfedf4188f9dbea9b59f862093a.jpg - 200 OK - 14751 bytes
2016-06-14 09:14:18,298: proxy - INFO - 10.10.10.15:56775 - GET image-glb.qpyou.cn:80/hubweb/hive_img/U/P/159209739/20160109/9110b3f9eee6b37008daf2828b426900.jpg - 200 OK - 6389 bytes
2016-06-14 09:14:19,713: proxy - INFO - 10.10.10.15:56776 - GET image-glb.qpyou.cn:80/hubweb/hive_img/U/P/133686836/20151213/909ecc8388daafe64f66836343a7b65e.jpg - 200 OK - 12147 bytes
2016-06-14 09:14:20,975: proxy - INFO - 10.10.10.15:56777 - GET image-glb.qpyou.cn:80////hubweb/avatar_img/03885/023537/016142a/a748a0491158040c415f2806732b8dd5_public_s.jpg?1438703572 - 200 OK - 7984 bytes
2016-06-14 09:14:21,934: proxy - INFO - 10.10.10.15:56778 - GET image-glb.qpyou.cn:80////hubweb/avatar_img/public/smon_27_s.png - 200 OK - 19907 bytes
2016-06-14 09:14:22,874: proxy - INFO - 10.10.10.15:56779 - GET image-glb.qpyou.cn:80////hubweb/avatar_img/public/noimage.png - 200 OK - 2731 bytes
2016-06-14 09:14:29,198: proxy - INFO - 10.10.10.15:56780 - GET image-glb.qpyou.cn:80////hubweb/avatar_img/03350/020127/0140b8f/873c9f9d7989714b37596afa16ec4f20_public_s.jpg?1423054197 - 200 OK - 9718 bytes
2016-06-14 09:14:29,773: proxy - INFO - 10.10.10.15:56781 - GET image-glb.qpyou.cn:80/hubweb/hive_img/U/P/149887601/20160312/b2e94d7b393bdf890dd626de1bcd2f0d.jpg - 200 OK - 8928 bytes
2016-06-14 09:14:30,429: proxy - INFO - 10.10.10.15:56782 - GET image-glb.qpyou.cn:80/hubweb/hive_img/U/P/140917404/20160106/dc957a460596565d0ba873591511a6d4.jpg - 200 OK - 13616 bytes
2016-06-14 09:14:30,998: proxy - INFO - 10.10.10.15:56783 - GET image-glb.qpyou.cn:80////hubweb/avatar_img/02d4e/01c511/011b2ac/73dc149d5723f703a31c2c1885ae510e_public_s.jpg - 200 OK - 13311 bytes
2016-06-14 09:14:31,727: proxy - INFO - 10.10.10.15:56784 - GET image-glb.qpyou.cn:80/hubweb/hive_img/U/P/112692412/20160609/3fe3f044017aafbf2deb86c7e9ee6a38.jpg - 200 OK - 16245 bytes
2016-06-14 09:14:32,901: proxy - INFO - 10.10.10.15:56785 - GET image-glb.qpyou.cn:80/hubweb/hive_img/U/P/129151824/20160218/45ba689c51ccaa72e708bb28768260d6.jpg - 200 OK - 12508 bytes
2016-06-14 09:14:37,249: proxy - INFO - 10.10.10.15:56763 - CONNECT p10-buy.itunes.apple.com:443
2016-06-14 09:17:02,263: proxy - INFO - 10.10.10.15:56787 - CONNECT p06-keyvalueservice.icloud.com:443
2016-06-14 09:17:03,794: proxy - INFO - 10.10.10.15:56788 - CONNECT p06-keyvalueservice.icloud.com:443
2016-06-14 09:17:08,232: proxy - INFO - 10.10.10.15:56789 - CONNECT configuration.apple.com:443
2016-06-14 09:17:12,213: proxy - INFO - 10.10.10.15:56790 - CONNECT p06-keyvalueservice.icloud.com:443
2016-06-14 09:17:38,598: proxy - INFO - 10.10.10.15:56786 - CONNECT p06-fmfmobile.icloud.com:443
`

**Comment by msteudel** [comment]
I tried commenting out these lines:
https://github.com/kakaroto/SWProxy/commit/a5eab05908e655db652dd3a8f8a67b3badc06a62#diff-4e41814cb10ce59e95537394d69e015a

And while I don't get the invalid format error it does stall out. I can set the proxy settings part way through the login process and it logs in, but it doesn't write out any files and I don't get the invalid format errors.

**Comment by Xzandro** [comment]
Did you look at this issue first? https://github.com/kakaroto/SWProxy/issues/105

**Comment by msteudel** [comment]
I did, though I didn't see any resolution, but I might've missed it.

**Comment by lstern** [comment]
Are you playing in english ?

**Comment by msteudel** [comment]
@lstern Yes I'm playing in english/global.

**Comment by HardcoreHostile** [comment]
I am getting the "Invalid Format" and "Network connectivity issues" messages ever since the game was updated on the 12th.

I am using SWProxy 0.99 on a Windows 10 Laptop and running iOS 9.3.2 on my iPhone 6S. I wanted to raise this issue but didn't know if it was just me getting it.

SWProxy worked 90% of the time before the new game update (occasionally the game wouldn't connect with the proxy settings entered, but most of the time it worked).

**Comment by lstern** [comment]
I think I managed to fix this issue.
https://github.com/lstern/SWProxy-plugins/releases/tag/7

**Comment by HardcoreHostile** [comment]
Can confirm that it now works with that release, thanks for the prompt fix!

**Comment by lstern** [comment]
Yes, all swproxy changes are applied on this repo first.
