### ISSUE TITLE
Unable to run the app on Windows 10

### ISSUE THREAD

**Issue by shuraou** [kakaroto/SWProxy#114]
Hi guys, 

I've downloaded the PC version and was trying to just run it and I get the following error message.

Crypto.Cipher._AES.pyd could not be extracted! 

Any idea how I could fix this issue?

My friend's PC which had upgraded from Windows 7 to 10 worked fine. 

I copied the same file from his PC just in case but I still get the same error message.

**Comment by Toosick** [comment]
The current release of SWProxy doesn't work but running the current source does work. I made a quick tutorial to run it yourself for the non tech people.

Windows tutorial, this worked in Windows 10 as well

Note: Uninstall Python 3.* if you have it and you don't want to cause any problems with installation
1. Download SWProxy source, extract it somewhere: https://github.com/kakaroto/SWProxy/archive/master.zip
2. Install this: https://www.python.org/downloads/release/python-279/
3. Install this: https://www.microsoft.com/en-us/download/details.aspx?id=44266
4. Put this into your CMD prompt: cd "C:\Python27\Scripts\" && pip install yapsy pycrypto dpkt
5. Right click the SWProxy.py file that was installed in step 1
6. Open with: IDLE
7. Click F5 while in the window with code
8. Success. Should be working as normal. Your own your own from here.

**Comment by oadrian2** [comment]
This doesn't seem to work. At least not for me. I'm using the master build as of 7/25/2016.

**Comment by Toosick** [comment]
This comment was 1 month ago. I don't know the current state of things.

**Comment by softbearlolz** [comment]
Hello, I follow your steps and get the following error message at step 7

Traceback (most recent call last):
  File "D:\SWProxy-master\SWProxy-master\SWProxy.py", line 3, in <module>
    from SWParser.smon_decryptor import decrypt_request, decrypt_response
  File "D:\SWProxy-master\SWProxy-master\SWParser\__init__.py", line 1, in <module>
    from parser import *
  File "D:\SWProxy-master\SWProxy-master\SWParser\parser.py", line 11, in <module>
    from SWPlugin import SWPlugin
  File "D:\SWProxy-master\SWProxy-master\SWPlugin.py", line 1, in <module>
    from yapsy import IPlugin
ImportError: No module named yapsy
>>> 


How can I solve it?

**Comment by Toosick** [comment]
@softbearlolz The current release of SWProxy works fine for me on Windows 10. Use that. Running from source isn't needed right now.

**Comment by softbearlolz** [comment]
But it still doesn't work on my windows 10.

**Comment by Toosick** [comment]
What is happening when you run this (https://github.com/kakaroto/SWProxy/releases/download/0.100/SWProxy-windows-2.zip)?

**Comment by softbearlolz** [comment]
It closed immediately. I cant see anything.

If i open it by CMD, the error messages is "Crypto.Cipher._AES.pyd could not be extracted!"

**Comment by Toosick** [comment]
Screenshot the error

**Comment by softbearlolz** [comment]
http://imgur.com/1ZjFl76 

you should copy the url, not click it.

**Comment by Toosick** [comment]
Never seen this error myself but going back to running from source.

Make sure both commands in step 4 work. I see from your errors your running from the D drive. Change the first part of step 4 to the D drive.

**Comment by Bratzmeister** [comment]
As in the error message you pasted above...you forgot to install yapsy. make sure you installed the python packages (via PIP or any other method) listed in the requirements.txt

**Comment by softbearlolz** [comment]
Thanks, I reinstalled windows 10 yesterday, and I can  open it .
