### ISSUE TITLE
Issue with SWProxy

### ISSUE THREAD

**Issue by techlock** [kakaroto/SWProxy#153]
Tried installing and setting up SWP today.
First issue was fetching ErrNo 22. Closed proxy out, followed previous resolved issue for resolution.

No data is being parsed at all by the looks of it and I can not open SWP with python idle.
What do I do next?

**Comment by techlock** [comment]
After leaving it running for approx. 5-10 minutes it fetched this error:

Traceback (most recent call last):
  File "SWParser\gui\gui.py", line 49, in openPCAP
  File "SWProxy.py", line 139, in parse_pcap
  File "site-packages\dpkt\pcap.py", line 121, in __init__
ValueError: invalid tcpdump header

**Comment by techlock** [comment]
Little bit more info :
Steps I took:
1. Download SWProxy source, extract it somewhere: https://github.com/kakaroto/SWProxy/archive/master.zip
2. Install this: https://www.python.org/downloads/release/python-279/
3. Install this: https://www.microsoft.com/en-us/download/details.aspx?id=44266
4. Put this into your CMD prompt: cd "C:\Python27\Scripts\" && pip install yapsy pycrypto dpkt
5. Right click the SWProxy.py file that was installed in step 1
6. Open with: IDLE
7. Click F5 while in the window with code
8. Success. Should be working as normal. You are on your own from here.

OS:
Windows 10

Device:
Samsung Galaxy Grand Prime

**Comment by techlock** [comment]
Update:
Tried with code version rather than windows, same problem with nothing coming up after multiple logins while proxy is running.
Device is connected to the proxy and everything.

**Comment by Jbag1489** [comment]
whenever I want to run from source, I go to the unpacked SWProxy folder, hold shift and right click then open a command window here. Then I just use 'python SWProxy.py'
