### ISSUE TITLE
Parser error in Generate Runes

### ISSUE THREAD

**Issue by casret** [kakaroto/SWProxy#158]
Looks like it was introduced in a70b2303766248b6f206330869e767d8553d63e7, once I revert that commit it works fine:

```
2016-11-27 22:38:26,506: root - ERROR - Exception while executing plugin "Generate Runes": string index out of range
Traceback (most recent call last):
  File "/Users/giaophan/git/SWProxy/SWPlugin.py", line 42, in call_plugins
    getattr(plugin.plugin_object, func_name)(*args)
  File "/Users/giaophan/git/SWProxy/plugins/GenerateRunes.py", line 235, in process_request
    parse_login_data(resp_json)
  File "/Users/giaophan/git/SWProxy/plugins/GenerateRunes.py", line 170, in parse_login_data
    optimizer_rune, csv_rune = map_rune(rune, rune_id_mapping[rune['rune_id']])
  File "/Users/giaophan/git/SWProxy/SWParser/parser.py", line 216, in map_rune
    "m_t": rune_effect_type(rune['pri_eff'][0]),
  File "/Users/giaophan/git/SWProxy/SWParser/parser.py", line 60, in monster_name
    awakened = int(uid[-2])
IndexError: string index out of range
```

**Comment by jons** [comment]
i'm seeing this as well.

**Comment by jake-griffin** [comment]
I can see the bug here. I will have a fix for it shortly.

**Comment by jons** [comment]
great! i forked, made a hack to bypass the issue, and submitted PR https://github.com/kakaroto/SWProxy/pull/160 for the time being. it will allow the user to get some fraction of the correct output for use with the rune optimizer.

**Comment by jake-griffin** [comment]
Actually, I'm having trouble reproducing the error. Not sure if I will be able to help with this one.

**Comment by kakaroto** [comment]
Thanks Jake for the fix, I've merged it.
