### ISSUE TITLE
Unable to download Dpkt python package

### ISSUE THREAD

**Issue by asramakr** [kakaroto/SWProxy#162]
When I run "sudo -H pip install pycrypto dpkt yapsy", all the packages but dpkt install. It gives me this error:

Collecting dpkt
  Using cached dpkt-1.8.8.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/tmp/pip-build-vca3792_/dpkt/setup.py", line 26
        print 'To build a Debian Package you must install stdeb (pip install stdeb)'
                                                                                   ^
    SyntaxError: invalid syntax

**Comment by asramakr** [comment]
When I try to run the parser, it says that:
Failed to load GUI dependencies. Switching to CLI mode.
