### ISSUE TITLE
Linux - Error when changing proxy port

### ISSUE THREAD

**Issue by Shinzah** [kakaroto/SWProxy#51]
**OS**: Ubuntu 14.04
**Python**: 2.7.6

Hi,

When launching SWProxy with -p parameter, an error it throwed and the process is stopped.

```
./SWProxy.py -g -d -p8085
########################################
# SWParser v0.98 - Summoners War Proxy # 
########################################
	Written by:
		KaKaRoTo

	Authors:
		Youness Alaoui
		Leonardo Stern
		Azrethos

	Plugins:
		Generate Visit Friend
		Print Unit Collection
		Barion Rune Efficiency Plugin
		Generate Runes
		Demo Plugin

Licensed under LGPLv3 and available at: 
	https://github.com/kakaroto/SWProxy

Running Proxy server at 91.121.211.44 on port [8085]
Traceback (most recent call last):
  File "./SWProxy.py", line 206, in <module>
    start_proxy_server(options)
  File "./SWProxy.py", line 174, in start_proxy_server
    p.run()
  File "/var/www/vhosts/shinsoft.fr/sw/swparser/SWProxy/proxy.py", line 554, in run
    self.socket.close()
AttributeError: 'HTTP' object has no attribute 'socket'
```

And the error in proxy.log
```
2016-03-22 17:11:30,946: proxy - ERROR - Exception while running the server TypeError('%d format: a number is required, not list',)
Traceback (most recent call last):
  File "SWProxy/proxy.py", line 540, in run
    logger.info('Starting server on %s, port %d' % (self.hostname, self.port))
TypeError: %d format: a number is required, not list
2016-03-22 17:11:30,947: proxy - INFO - Closing server socket
```

**Comment by edroot** [comment]
./SWProxy.py -g -d -p8085
change
./SWProxy.py -g -d -p 8085

**Comment by Shinzah** [comment]
@edroot Already did it, and the same error is throwed.

**Comment by edroot** [comment]
change string
parser.add_argument('-p', '--port', type=int, help='Port number', default=8080, nargs='+')
to
parser.add_argument('-p', '--port', type=int, help='Port number', default=8085, nargs='+')

and run
./SWProxy.py -g -d

**Comment by Shinzah** [comment]
@edroot Thank you, that what's i've done to change the port, and it work this way. :+1:
