### ISSUE TITLE
ImportError: No module named yapsy

### ISSUE THREAD

**Issue by msteudel** [kakaroto/SWProxy#99]
Im not sure what I did wrong this time, but here's the output of trying to install it. I am running Python 2.7.8 ... do you think that's it?

```
msteudel@Marks-MacBook-Pro swproxy (master) $ sudo -H pip install pycrypto dpkt yapsy
Collecting pycrypto
  Downloading pycrypto-2.6.1.tar.gz (446kB)
    100% |████████████████████████████████| 450kB 2.0MB/s 
Collecting dpkt
  Downloading dpkt-1.8.7-py2-none-any.whl (112kB)
    100% |████████████████████████████████| 122kB 4.4MB/s 
Collecting yapsy
  Downloading Yapsy-1.11.223.tar.gz (80kB)
    100% |████████████████████████████████| 81kB 5.1MB/s 
Installing collected packages: pycrypto, dpkt, yapsy
  Running setup.py install for pycrypto ... done
  Running setup.py install for yapsy ... done
Successfully installed dpkt-1.8.7 pycrypto-2.6.1 yapsy-1.11.223
msteudel@Marks-MacBook-Pro swproxy (master) $ python SWProxy.py 
Traceback (most recent call last):
  File "SWProxy.py", line 3, in <module>
    from SWParser.smon_decryptor import decrypt_request, decrypt_response
  File "/Users/msteudel/Documents/wwwroot/swproxy/swproxy/SWParser/__init__.py", line 1, in <module>
    from parser import *
  File "/Users/msteudel/Documents/wwwroot/swproxy/swproxy/SWParser/parser.py", line 11, in <module>
    from SWPlugin import SWPlugin
  File "/Users/msteudel/Documents/wwwroot/swproxy/swproxy/SWPlugin.py", line 1, in <module>
    from yapsy import IPlugin
ImportError: No module named yapsy
```

**Comment by kakaroto** [comment]
You're on a mac, so try with 'easy_install' instead of pip. I don't know why it installs it but still fails to run. Otherwise, why not just use the precompiled binaries for mac ?

**Comment by msteudel** [comment]
I tried all those. In the end I installed python using hombrew and setup virtual envs and have it running in there ... just in time for FRR!

**Comment by msteudel** [comment]
This is the guide I ended up using to get it running: https://hackercodex.com/guide/python-development-environment-on-mac-osx/
